limmit_size_pic: 5
accept_picture: "image/jpeg,image/gif,image/png"
remember: "1"
per_page: 10
user:
  max_length_name: 50
  max_length_email: 255
  min_length_password: 6
gravatar:
  size: 50
  size_list: 30
reset_expired: 2
micropost:
  length_text: 140
